### ISSUE TITLE
交流Flutter for Windows

### ISSUE THREAD

**Issue by Sunbreak** [liudonghua123/flutter_app#3]
Hi
我在字节客户端架构组负责Flutter for PC，在https://github.com/Squirrel/Squirrel.Windows/issues/1672 看到您对Flutter for Windows了解颇深

希望能加个好友，一起研究。我们已经组织了一个小群，有字节、阿里、滴滴、好未来等在探索Flutter for PC的团队成员

微信：wk2311007
工作邮箱：wangkun.sunbreak@bytedance.com

**Comment by liudonghua123** [comment]
ok 😄
